### ISSUE TITLE
Find-FLowChartNodes throw NullReferenceException when the 'ScriptBlock' parameter is null

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/FlowChartCore#20]
```Powershell
Find-FLowChartNodes -ScriptBlock $null
#Find-FLowChartNodes : La référence d'objet n'est pas définie à une instance d'un objet.
```

**Comment by LxLeChat** [comment]
```
PS > Find-FLowChartNodes -ScriptBlock $null
Find-FLowChartNodes: Parameter cannot be null (Parameter 'ScriptBlock')
```

j'ai ajouté un if dans la fonction .. pas sur que ça soit la meilleur façon de faire ...

**Comment by LxLeChat** [comment]
J'ai  changé l'exception en ``ArgumentNullException``
``Find-FLowChartNodes: Value cannot be null. (Parameter 'ScriptBlock')``

**Comment by LaurentDardenne** [comment]
Et avec un attribut de validation ?

**Comment by LxLeChat** [comment]
J y ai pensé mais jai pas encore trouvé comment ça s implémentait en c# xD
C une rustine 😄

Je chercherai demain si j ai un peu de temps! 
Je vais surtout me concentrer sur le readme. J avais ouvert des trucs facile (hacktoberfest) pour le frpsug mais ils ont pas l air chaud les coquins!!

**Comment by LxLeChat** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.validatenotnullattribute?view=powershellsdk-7.0.0
Peut-être ça .. !

**Comment by LxLeChat** [comment]
voila c'est vachement mieux quand même!
```powershell
PS > Find-FLowChartNodes -ScriptBlock $null
Find-FLowChartNodes: Cannot validate argument on parameter 'ScriptBlock'. The argument is null. Provide a valid value for the argument, and then try running the command again.
PS > $error[0] | select *

PSMessageDetails      :
Exception             : System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on
                        parameter 'ScriptBlock'. The argument is null. Provide a valid value for the argument, and
                        then try running the command again.
                         ---> System.Management.Automation.ValidationMetadataException: The argument is null. Provide
                        a valid value for the argument, and then try running the command again.
                           at System.Management.Automation.ValidateNotNullAttribute.Validate(Object arguments,
                        EngineIntrinsics engineIntrinsics)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                        parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                        parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParamet
                        erInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32
                        parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter,
                        ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32
                        parameterSets, Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoV
                        alidation(Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Co
                        llection`1 arguments)
                           at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                           at System.Management.Automation.CommandProcessor.Prepare(IDictionary
                        psDefaultParameterValues)
                           at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary
                        psDefaultParameterValues)
                           at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                           at
                        System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                        input)
                        --- End of stack trace from previous location where exception was thrown ---
                           at
                        System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                        input)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean
                        ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
                        CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
TargetObject          :
CategoryInfo          : InvalidData: (:) [Find-FLowChartNodes], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationError,FlowChartCore.Cmdlets.FindFlowChartNodes
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

et si le script block est "vide" et non pas null.. donc ça: ``-scriptblock {}``, on retourne null... pareil si un fichier ps1 est vide.

**Comment by LxLeChat** [comment]
What do you think ?
pour le coup de retourner null, si le scriptblock est vide je trouve ça pas mal ... parce que avant, ça retournait une ``List<Node>`` vide

**Comment by LaurentDardenne** [comment]
> What do you think ?

Que du bien ;-)

> pour le coup de retourner null, si le scriptblock est vide je trouve ça pas mal ... parce que avant, ça retournait une `List<Node>` vide

Réponse courte : oui
Réponse de normand: ça dépend...
Sans écrire [20 pages sur le sujet](https://github.com/LaurentDardenne/Tutorial/blob/master/Null%20ce%20n'est%20pas%20rien/NullCeNestPasRien.pdf), ceci est à considérer :
```powershell
$List = New-Object System.Collections.Generic.List[string]
$List|Foreach-Object {"Hello"}
$List =$null
$List|Foreach {'suite du traitement'}

$AutomationNull = [System.Management.Automation.Internal.AutomationNull]::Value
$AutomationNull|Foreach {'suite du traitement'}
```
 [Selon le SDK ](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.internal.automationnull?view=powershellsdk-1.1.0) on doit dans ce cas renvoyer  [System.Management.Automation.Internal.AutomationNull]::Value

La suite :
https://github.com/PowerShell/PowerShell/issues/9997#issuecomment-505569435

Avec _un trou dans la raquette_ :
https://github.com/PowerShell/PowerShell/issues/9150#issuecomment-474650803

Si on teste un get-process toto, on obtient une exception et 'test'|select-string '\s' on obtient $null.
Il ne faut pas qu'on reçoive $null ou une liste vide, ce que j'ai déjà rencontré.

**Comment by LxLeChat** [comment]
enfait je renvoie pas null, je renvoie rien 
```powershell
ListOfNodes =  FlowChartCore.Utility.ParseScriptBlock(ScriptBlock);
if (ListOfNodes.Count > 0 ){
    WriteObject(ListOfNodes);
}
```

du coup je sais pas si ça compte ...

faut que je lise tout ça

**Comment by LaurentDardenne** [comment]
> ```
> 
> du coup je sais pas si ça compte ...
> 
C'est correct en l'état, un petit contrôle rapido :
```powershell
$sb={}
$null -eq (Find-FLowChartNodes -ScriptBlock $Sb)
#True
[System.Management.Automation.Internal.AutomationNull]::Value -eq (Find-FLowChartNodes -ScriptBlock $Sb)
#True
Find-FLowChartNodes -ScriptBlock $Sb|% {'test'}
#ras

$t=Find-FLowChartNodes -ScriptBlock $Sb
$T|% {'test'}
#ras

$t=$null
$T|% {'test'}
#test
```
Dans ton cas le runtime PS émet implicitement _System.Management.Automation.Internal.AutomationNull_ (enfin je supposes je n'ai pas lu tout le code source de PS ...)
En revanche avec l'ajout d'un _else null_ (on émet null explicitement) le pb se posera ( je n'ai pas pris le temps de vérifier en recompilant).

Ma réponse précédente complique un peu les choses, mais ce n'est pas plus mal de vérifier ce point je trouve.

**Comment by LxLeChat** [comment]
> Dans ton cas le runtime PS émet implicitement System.Management.Automation.Internal.AutomationNull (enfin je supposes je n'ai pas lu tout le code source de PS ...)
🤣 

du coup j'ai fait un test bidon, avec un fichier vide et un fichier qui contient du code
``> gci *.ps1 | Find-FLowChartNodes | New-FLowChartGraph``
et ça me sort un seul graph ..
si je rempli le deuxième fichier, j'ai bien 2 graph

**Comment by LxLeChat** [comment]
bon du coup je crois que je peux clôturer cette issue !
@LaurentDardenne un truc que j aurais manqué ?

**Comment by LaurentDardenne** [comment]
Non je ne pense pas.
